### ISSUE TITLE
提示记账成功，但未同步到钱迹

### ISSUE THREAD

**Issue by z1298808165** [AutoAccountingOrg/AutoAccounting#160]
日志显示解析出错
```
[ 2024-05-09 23:39:23 ]
[ DefaultDispatcher-worker-3 ] (BillUtils.kt:77)  解析自动记账出错
[ DefaultDispatcher-worker-3 ] (BillUtils.kt:77)  java.lang.NullPointerException: fromJson(...) must not be null
[ DefaultDispatcher-worker-3 ] (BillUtils.kt:77)    at net.ankio.auto.app.BillUtils$syncBillInfo$2.invokeSuspend(BillUtils.kt:75)
[ DefaultDispatcher-worker-3 ] (BillUtils.kt:77)    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[ DefaultDispatcher-worker-3 ] (BillUtils.kt:77)    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
[ DefaultDispatcher-worker-3 ] (BillUtils.kt:77)    at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
[ DefaultDispatcher-worker-3 ] (BillUtils.kt:77)    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
[ DefaultDispatcher-worker-3 ] (BillUtils.kt:77)    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
[ DefaultDispatcher-worker-3 ] (BillUtils.kt:77)    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
[ DefaultDispatcher-worker-3 ] (BillUtils.kt:77)    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
[ DefaultDispatcher-worker-3 ] (BillUtils.kt:77)    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
[ DefaultDispatcher-worker-3 ] (BillUtils.kt:77)  
```

**Comment by z1298808165** [comment]
解析自动记账出错似乎是因为备注格式的问题，例如我备注格式是`【商户名称】-【商品名称】`但其中可能某一个获取到的值为空，所以导致了账单解析出错

**Comment by AnkioTomas** [comment]
这个错误是合并自动记账到待记录账单的时候发生，不影响使用，如果多次发生，请提供 /sdcard/Android/data/net.ankio.auto.xposed/cache/shell/auto\_bills.txt文件
