### ISSUE TITLE
beta10 自动分类功能报错

### ISSUE THREAD

**Issue by z1298808165** [AutoAccountingOrg/AutoAccounting#228]
步骤：
1.自动记账中开启自动分类功能
2.找个账单数据进行记账
3.此时自动记账的日志页面显示报错

PS：账单中还是会记录成功

日志如下：
```
[ 2024-05-13 13:34:38 ] [微信][J]：微信数据：{"mMap":{"msgSvrId":3109386040438822968,"isSend":0,"msgSeq":816097258,"status":3,"talker":"wxid_v7uaxwuwfahs21","talkerId":12163,"lvbuffer":[123,0,0,0,0,0,0,0,-90,60,109,115,103,115,111,117,114,99,101,62,10,9,60,98,105,122,102,108,97,103,62,48,60,47,98,105,122,102,108,97,103,62,10,9,60,112,117,97,62,49,60,47,112,117,97,62,10,9,60,115,105,103,110,97,116,117,114,101,62,86,49,95,122,52,99,99,65,107,52,107,124,118,49,95,122,52,99,99,65,107,52,107,60,47,115,105,103,110,97,116,117,114,101,62,10,9,60,116,109,112,95,110,111,100,101,62,10,9,9,60,112,117,98,108,105,115,104,101,114,45,105,100,62,60,47,112,117,98,108,105,115,104,101,114,45,105,100,62,10,9,60,47,116,109,112,95,110,111,100,101,62,10,60,47,109,115,103,115,111,117,114,99,101,62,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,125],"flag":0,"type":1,"msgId":10336262,"bizChatId":-1,"content":"二十分钟","bizClientMsgId":"","createTime":1715578477000}} table:message arg:msgId

[2024-05-13 13:34:46][E][ DefaultDispatcher-worker-5 ] (Engine.kt:134) 分类脚本执行出错: End of input at character 0 of org.json.JSONException: End of input at character 0 of   at org.json.JSONTokener.syntaxError(JSONTokener.java:469)  at org.json.JSONTokener.nextValue(JSONTokener.java:101)  at org.json.JSONObject.<init>(JSONObject.java:168)  at org.json.JSONObject.<init>(JSONObject.java:185)  at net.ankio.auto.app.js.Engine$category$2.invokeSuspend(Engine.kt:114)  at net.ankio.auto.app.js.Engine$category$2.invoke(null:8)  at net.ankio.auto.app.js.Engine$category$2.invoke(null:4)  at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61)  at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)  at kotlinx.coroutines.BuildersKt.withContext(null:1)  at net.ankio.auto.app.js.Engine.category(Engine.kt:94)  at net.ankio.auto.app.js.Engine$analyze$2.invokeSuspend(Engine.kt:41)  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)  at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)  at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
```

**Comment by AnkioTomas** [comment]
lsp里面点击重新优化看看

**Comment by z1298808165** [comment]
> lsp里面点击重新优化看看

还是报错
![15360887d97e8fd112e95284f1d7e27](https://github.com/AutoAccountingOrg/AutoAccounting/assets/25720725/b6a87a92-e7aa-4e9b-b196-7dc112725f3e)

**Comment by AnkioTomas** [comment]
找一下另一个日志，在sdcard/Android/data/net.ankio.auto.xposed/cache/shell/daemon.log

**Comment by z1298808165** [comment]
> 找一下另一个日志，在sdcard/Android/data/net.ankio.auto.xposed/cache/shell/daemon.log

[daemon.log](https://github.com/AutoAccountingOrg/AutoAccounting/files/15289886/daemon.log)

**Comment by z1298808165** [comment]
补充：自定义分类规则时，无法选择账本的分类，只有一个“其他”
