### ISSUE TITLE
配置丢失，无法恢复

### ISSUE THREAD

**Issue by Adlyq** [AutoAccountingOrg/AutoAccounting#692]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

时不时会丢配置，持续好几个版本了;webdav无法恢复配置

### 重现步骤

```bash
有时候打开自动记账会发现丢失所有配置，要重新设置

当前版本备份到云的设置，无法恢复，提示[服务端没有备份文件]
```

### 相关环境说明

自动记账  4.0.0-Canary.20241021032044
系统  a13，5.15.148， hyperos1.0.13.0

### 日志内容

```
Exception: Unexpected code Response{protocol=h2, code=404, message=, url=https://dav.jianguoyun.com/dav/AutoAccounting/backup_4.0.0-canary.20241010151115%20-%20xposed(202)_1728574595726.pk}
java.io.IOException: Unexpected code Response{protocol=h2, code=404, message=, url=https://dav.jianguoyun.com/dav/AutoAccounting/backup_4.0.0-canary.20241010151115%20-%20xposed(202)_1728574595726.pk}
  at net.ankio.auto.request.RequestsUtils$download$2.invokeSuspend(RequestsUtils.kt:269)
  at net.ankio.auto.request.RequestsUtils$download$2.invoke(null:8)
  at net.ankio.auto.request.RequestsUtils$download$2.invoke(null:4)
  at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61)
  at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
  at kotlinx.coroutines.BuildersKt.withContext(null:1)
  at net.ankio.auto.request.RequestsUtils.download(RequestsUtils.kt:253)
  at net.ankio.auto.storage.BackupUtils$downFromWebDav$2.invokeSuspend(BackupUtils.kt:359)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
  at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
  at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该错误尚未被报告。

**Comment by AnkioTomas** [comment]
丢失配置需要更多的信息：
比如你在上一次关闭自动记账的时候是如何关闭的，就目前为止我没有遇到过这个问题。

**Comment by Adlyq** [comment]
很久才会打开一次自动记账，下次我注意一下，就是没法提供日志，日志是空的

**Comment by AnkioTomas** [comment]
> 很久才会打开一次自动记账，下次我注意一下，就是没法提供日志，日志是空的

可能需要再确认一下问题，

日志空的说明和自动记账服务通信可能出现了问题而不是自动记账的配置（设置项）出现了问题

下次建议用logcat抓一下自动记账的日志

`adb logcat`

**Comment by Adlyq** [comment]
![Screenshot_2024-10-29-23-01-12-219_net.ankio.auto.xposed.jpg](https://github.com/user-attachments/assets/a00cc479-0a97-4d01-a40a-071063bdef9f)

![Screenshot_2024-10-29-23-01-16-271_net.ankio.auto.xposed.jpg](https://github.com/user-attachments/assets/ebe3c001-eba4-44fd-b2c1-8695710e287d)

```Handler UncaughtException
java.lang.NullPointerException: null
  at net.ankio.auto.ui.fragment.HomeFragment.getBinding(HomeFragment.kt:66)
  at net.ankio.auto.ui.fragment.HomeFragment.bindRuleUI(HomeFragment.kt:256)
  at net.ankio.auto.ui.fragment.HomeFragment.access$bindRuleUI(HomeFragment.kt:64)
  at net.ankio.auto.ui.fragment.HomeFragment$checkRuleUpdate$2$updateDialog$1$1.invoke(HomeFragment.kt:299)
  at net.ankio.auto.ui.fragment.HomeFragment$checkRuleUpdate$2$updateDialog$1$1.invoke(HomeFragment.kt:298)
  at net.ankio.auto.App$Companion.runOnUiThread$lambda$0(App.kt:124)
  at net.ankio.auto.App$Companion.$r8$lambda$X4pwSatbmibuiZv4m6Woq-X6MXw(null:0)
  at net.ankio.auto.App$Companion$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
  at android.os.Handler.handleCallback(Handler.java:958)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loopOnce(Looper.java:224)
  at android.os.Looper.loop(Looper.java:318)
  at android.app.ActivityThread.main(ActivityThread.java:8777)
  at java.lang.reflect.Method.invoke(Method.java:-2)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

**Comment by Adlyq** [comment]
在发生刘培植之后，重启app，无效，过一段时间会弹出服务端连不上，重启手机无法恢复配置，能连上服务
